### ISSUE TITLE
bug: yard ignores @!attribute + alias_method

### ISSUE THREAD

**Issue by jimtng** [ccutrer/openhab-jrubyscripting#124]
@!attribute followed by a `def` works

However, none of our @!attributes that are followed by alias_method are included in the generated doc.

**Comment by ccutrer** [comment]
If we have any of those, we need to move them to not be associated with the alias_method. YARD doesn't know about the (java) method that's being copied, so just kind of ignores the new method

**Comment by jimtng** [comment]
Check out ThingStatusInfoEvent and ThingStatusInfoChangedEvent 
All their alias_method attributes aren't documented.

I tried separating the alias_method lines but that didn't work.

**Comment by jimtng** [comment]
It seems that only those two Thing events above and `ItemCommandEvent` are affected / using @!attribute + alias_method.
