### ISSUE TITLE
transform syntactic sugar?

### ISSUE THREAD

**Issue by ccutrer** [ccutrer/openhab-jrubyscripting#140]
Following up from https://github.com/boc-tothefuture/openhab-jruby/issues/9

```ruby
Transform.map("mymap.map", 0)
```

might be useful?

```ruby
NumberItem1.state.map("mymap.map")
```

maybe too, but would it be better to just have something like

```ruby
NumberItem1.state_string
```

 or something that simply takes the state pattern for the item (including a transformation if it's defined) and returns that instead?

**Comment by jimtng** [comment]
> or something that simply takes the state pattern for the item (including a transformation if it's defined) and returns that instead?

I thought item.state.toString is supposed to do that

**Comment by ccutrer** [comment]
no, that simply calls stringifies a raw state, with no context of the item's state description
