### ISSUE TITLE
HTTP actions not available on the top-level

### ISSUE THREAD

**Issue by jimtng** [ccutrer/openhab-jrubyscripting#44]
I can no longer use HTTP from top level like this:

```ruby
require 'openhab/dsl'

HTTP.sendHttpGetRequest("https://www.google.com")
```

It has to be prefixed with `OpenHAB::Core::Actions::`

**Comment by jimtng** [comment]
I see that the actual methods are available on the top level now, i.e.
```ruby
require 'openhab/dsl'

send_http_get_request(...)
```
This should probably be included in the Breaking change list

**Comment by ccutrer** [comment]
I’m having buyer’s remorse with my “make action methods accessible at the top level”.  like with ephemeris. I don’t want any of those methods accessible on the top level now that I’ve got them wrapped up so nicely on date/time related classes. and there’s probably Semantics methods ending up on top-level now. So re-opening to discuss.

Btw, HTTP is _not_ available at top level because it's not truly an action anymore. it's a Rules DSL-only action (as are Exec and Ping). I think they didn't expose them to JSR223 with all the other actions, because they expect the scripting language you're using to have a more direct and simple method for these actions.

**Comment by ccutrer** [comment]
oh, it is now. I wrote f908e9976fe65fce4127317196071a32fdde6e01 specifically to address these "deprecated" actions.

Okay, but why are `Voice`, `Audio`, and to a lesser extent, `NotificationAction` special? I'd almost vote that the first two should have their ruby-nicety helper methods relegated to being added to the action itself, like I've (as of the current revision of the PR) done with the Ephemeris PR (https://github.com/ccutrer/openhab-jrubyscripting/pull/132). `notify` feels common and more of a departure from the provided Action to still have a helper method. Definitely open to feedback there, though.

**Comment by jimtng** [comment]
I'm in favour of NOT having action methods go in the top-level, i.e.
```ruby
send_http_get_request(....) # This shouldn't be here

# Instead, it should remain as
HTTP.send_http_get_request(...)
```

My only concern is that the action methods are polluting the top-level.



> Btw, HTTP is _not_ available at top level because it's not truly an action anymore. it's a Rules DSL-only action (as are Exec and Ping). I think they didn't expose them to JSR223 with all the other actions, because they expect the scripting language you're using to have a more direct and simple method for these actions.

The old jython helper libraries supports using HTTP/Exec etc and so that's where this came from.




> Okay, but why are `Voice`, `Audio`, and to a lesser extent, `NotificationAction` special?

I think it's because they are core-provided actions as opposed to binding provided actions. This probably goes back to when bindings can introduce their own "top level" actions, i.e. not directly tied to a thing.



> I'd almost vote that the first two should have their ruby-nicety helper methods relegated to being added to the action itself, like I've (as of the current revision of the PR) done with the Ephemeris PR (#132). `notify` feels common and more of a departure from the provided Action to still have a helper method. Definitely open to feedback there, though.

Are you referring to the methods that we have created, i.e.`say`, `play_sound`, `play_stream`, etc? TBH I've always felt that they are a bit strange to be on the top-level. I added them into the library very early on when I had just migrated from rulesdsl/jython. Even in Jython they were called using `Voice.say`.

I'm open to breaking changes that would move them back into their classes, as it would be cleaner that way.

**Comment by ccutrer** [comment]
Okay, we're good now. The original issue was still fixed anyway, that HTTP is available at top level
