### ISSUE TITLE
automatic rule uid making it difficult to find the rule

### ISSUE THREAD

**Issue by jimtng** [ccutrer/openhab-jrubyscripting#58]
The automatic uid / name inference is making it hard to find where the rule is located. I prefer the old rulefile:line_number way of rule uid inference. Perhaps it can be combined - rule_name (rulefile:linenumber) ?

**Comment by ccutrer** [comment]
hmm, this is a good point. I'll think on it a bit. I changed it to make it easier to use `trigger_rule` (both in specs and in rules themselves), without worrying about the rule moving breaking it. but I definitely agree that file:line is more useful for looking at logs (and I was going to say the UI too, but it's easy enough to open up a rule and see its full details in the UI). maybe I can come up with a compromise. Are you mainly looking at logs and finding it difficult to go from log line to rule source?

**Comment by jimtng** [comment]
Yes, it's exactly because of the logs. I can find the rule using regex, replacing _ with .*
