### ISSUE TITLE
Time rounding bug

### ISSUE THREAD

**Issue by jimtng** [ccutrer/openhab-jrubyscripting#65]
In some specs and possibly also actual library code, time / zoneddatetime is converted to_i and the result is relied upon for some comparison / verification. This value seems to suffer from rounding (from nanoseconds to seconds?) and therefore can sometimes be off by 1.

I'm keeping track of where I have encountered this:

```
  1) OpenHAB::Core::Timer with real timers supports absolute ZonedDateTime
     Failure/Error: expect(t.execution_time.to_i).to eql time.to_i
     
       expected: 1893456000
            got: 1893455999
     
       (compared using eql?)
     Shared Example Group: "Timer interface" called from ./spec/openhab/core/timer_spec.rb:215
     # ./spec/openhab/core/timer_spec.rb:62:in `block in <main>'
```

```
1) OpenHAB::Core::Timer with real timers supports Time
     Failure/Error: expect(t.execution_time.to_i).to eq time.to_i
       expected: 1893456000
            got: 1893455999
       (compared using ==)
     Shared Example Group: "Timer interface" called from ./spec/openhab/core/timer_spec.rb:195
     # ./spec/openhab/core/timer_spec.rb:68:in `block in <main>'
```

**Comment by ccutrer** [comment]
Might I introduce you to https://relishapp.com/rspec/rspec-expectations/v/2-5/docs/built-in-matchers/be-within-matcher. Which should work with durations, so the to_i would no longer be needed.
